version: '3.7'
services:
  app:
    container_name: app
    build: .
    image: app:22
    ports:
      - 8080:8080
  mongo:
    image: mongo:latest
    restart: always
    container_name: mongoDB
    ports:
      - 8081:8081
