version: '3.7'
services:
  app:
    container_name: app
    build: .
    image: app:1
    ports:
      - 8080:8080
  mongo:
    image: mongo:latest
    container_name: mongoDB
    ports:
      - 27017:27017
